config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources "recipes"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   def index
  @recipes = Recipe.all
     if(params["ingredient"])
     @recipes = @recipes.where("ingredients LIKE :query", query: "%#{params["ingredient"]}%")
   end
  end
   def show
   @recipe = Recipe.find(params["id"])
   end

   def new
   end

   def create
   r = Recipe.new
   r.name = params["recipe"]["name"]
   r.ingredients = params["recipe"]["ingredients"]
   r.description = params["recipe"]["description"]
   r.save
   flash[:notice] = "Przepis dodany"
   redirect_to(recipe_path(r))
   end

    def edit
      @recipe = Recipe.find(params["id"])
    end

    def update
    r = Recipe.find(params["id"])
    r.name = params["recipe"]["name"]
   r.ingredients = params["recipe"]["ingredients"]
   r.description = params["recipe"]["description"]
   r.save
   flash[:notice] = "Przepis zmieniony"
   redirect_to(recipe_path(r))
    end

  def destroy
    r = Recipe.find(params["id"])
    r.destroy
    flash[:notice] = "Przepis skasowany"
    redirect_to(recipes_path)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  @recipes = Recipe.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="flash-notice">
   <%= flash[:notice] %>
  </div>
  
<%= yield %> 

</body>
</html>

app/views/recipes/edit.html.erb
<%= form_for(@recipe) do |form| %>
 <p><%= form.label("name") %></p>
 <p><%= form.text_field("name") %></p>
 <p><%= form.label("ingredients") %></p>
 <p><%= form.text_field("ingredients") %></p>
 <p><%= form.label("description") %></p>
 <p><%= form.text_area("description") %></p>
 <p><%= form.submit("Zapisz") %></p>
<% end %>
<p><%= link_to("Powrót", recipes_path) %></p>

app/views/recipes/index.html.erb
<div>
 <%= form_tag(recipes_path, method: "get") do %>
   <%= text_field_tag "ingredient", params["ingredient"] %>
   <%= submit_tag "szukaj" %>
  <% if(params["ingredient"]) %>
     <%= link_to("resetuj", recipes_path) %>
  <p><%= link_to("Powrót", recipes_path) %></p>
 <% end %>
  <% end %>
</div>


<h1>Moje przepisy</h1>
<div>
  <% for r in @recipes %>
    <h2><%= r.name %></h2>
   <p><%= r.ingredients %></p>
  <p><%= link_to("zobacz przepis", recipe_path(r.id)) %></p>
 <% end %>
</div>

<div></div>
<p><%= link_to("dodaj przepis", new_recipe_path) %></p>

app/views/recipes/new.html.erb
<%= form_for(Recipe.new) do |form| %>
 <p><%= form.label("name") %></p>
 <p><%= form.text_field("name") %></p>
 <p><%= form.label("ingredients") %></p>
 <p><%= form.text_field("ingredients") %></p>
 <p><%= form.label("description") %></p>
 <p><%= form.text_area("description") %></p>
 <p><%= form.submit("Zapisz") %></p>
<% end %>
<p><%= link_to("Powrót", recipes_path) %></p>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<p><%= @recipe.ingredients %></p>
<p><%= @recipe.description %></p>
<p><a href="/recipes">wróc</a></p>

<p><%= link_to("edytuj", edit_recipe_path(@recipe)) %></p>
<p><%= link_to("usuń", recipe_path(@recipe), "method" => "delete") %></p>

app/views/welcome/index.html.erb
<h1>My Recipes</h1>
<div>
  <% for x in @recipes %>
    <h2><%= x.name %></h2>
   <p><%= x.ingredients %></p>
   <p><%= x.description %></p>
 <% end %>
</div>